### ISSUE TITLE
Add Odoo exceptions to models.pyi

### ISSUE THREAD

**Issue by jcfernandez-890825** [odoo-ide/odoo-stubs#10]
![image](https://user-images.githubusercontent.com/28876647/148953275-5da75cbe-63f5-40a2-b6c0-cc3b2a2deae6.png)

As you can you can see there's an import for Odoo exceptions in /src/odoo/odoo/models.py
![image](https://user-images.githubusercontent.com/28876647/148953666-316a6505-5124-4667-9508-efb2809d871f.png)

**Comment by trinhanhngoc** [comment]
@jcfernandez-890825   I will add those imports, be patient =))

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 ,

This issue will be fixed in the next version of the Odoo plugin without any changes to odoo-stubs.

**Comment by trinhanhngoc** [comment]
The new version 2022.2 just released! https://odoo-ide.com/blog/news-1/pycharm-odoo-2022-2-3

**Comment by jcfernandez-890825** [comment]
Again, love your work. I'm currently downloading the new release. Can't wait to see the new features.
