### ISSUE TITLE
VSCode?

### ISSUE THREAD

**Issue by tooolbox** [odoo-ide/odoo-stubs#11]
I do not have PyCharm and I'm interested in working with these stubs in VSCode with Pylance.  Do these work for that purpose?

**Comment by trinhanhngoc** [comment]
Hi @tooolbox You are free to use these stubs with VSCode. However, I am not sure if these stubs are useful for VSCode.

**Comment by tooolbox** [comment]
Well alright, I will have to check it out.  Thanks.
