### ISSUE TITLE
Missing definitions for v10, v11, v12.

### ISSUE THREAD

**Issue by jcfernandez-890825** [odoo-ide/odoo-stubs#13]
For v10:
```
    _fields: Dict[str, fields.Field]
    _ids: List[int]
```

For v11, v12:
```
    _ids: List[int]
```

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 , I am rewriting all stub files with fully typed annotations including those you mentioned above.

**Comment by jcfernandez-890825** [comment]
Awesome, that will help a lot.
