### ISSUE TITLE
Unresolved attribute reference 'sale_get_order' for class 'Website'

### ISSUE THREAD

**Issue by jcfernandez-890825** [odoo-ide/odoo-stubs#15]
`odoo/addons/website_sale_delivery/controllers/main.py`
![image](https://github.com/odoo-ide/odoo-stubs/assets/28876647/6e68b0aa-5fe9-4c39-9685-190b13080eb0)

To fix this:
![image](https://github.com/odoo-ide/odoo-stubs/assets/28876647/11715be4-7a10-4186-99dd-35102e1ef098)

**Comment by trinhanhngoc** [comment]
@jcfernandez-890825, Thank you for the information. I recently updated `odoo-stubs` for better compatibility with VSCode. However, some changes around the recordset type hint seem to cause problems with PyCharm. I will investigate this further.

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 The new version 2023.5.5 has been released with some fixes related to type hints for recordsets.
