### ISSUE TITLE
Javascript import improvement

### ISSUE THREAD

**Issue by nabilragab** [odoo-ide/odoo-stubs#16]
when importing in javascript a module like:

    const {_lt} = require("@web/core/l10n/translation");

the manifest could be missing the 'depends': 'web'

yet still show the import in dropdown, generally you have improved this on the field with python which is great.

**Comment by trinhanhngoc** [comment]
Hi @nabilragab , I don't quite understand what you mean. I am assuming that you are talking about the behavior of the PyCharm plugin. The plugin takes into account module dependencies and [`auto_install`](https://www.odoo.com/documentation/16.0/developer/reference/backend/module.html) modules when resolving imports, symbols,... This applies to both Python and JavaScript.
