### ISSUE TITLE
Another way to set the path for Odoo Stubs without placing it inside the Odoo directory.

### ISSUE THREAD

**Issue by daonamutc1** [odoo-ide/odoo-stubs#17]
I found another way to set the path for Odoo Stubs without placing it inside the Odoo directory.
Below is how I organize the directories:
![image](https://github.com/odoo-ide/odoo-stubs/assets/55737816/91c90ebc-6664-41c4-9d23-3466d715684f)
![image](https://github.com/odoo-ide/odoo-stubs/assets/55737816/d32ecd6b-1a0a-43cf-978c-c9ad00ecf2e1)
![image](https://github.com/odoo-ide/odoo-stubs/assets/55737816/c6ac20d0-101e-4712-872e-2e10f4bbff93)

Please replace the paths accordingly to match the directory structure you have.

**Comment by trinhanhngoc** [comment]
Hello @daonamutc1 . In the next version (0.6.0), the Odoo extension will have built-in stubs, so we won't need to configure odoo stubs manually in VSCode anymore.

**Comment by tranngocson1996** [comment]
> Hello @daonamutc1 . In the next version (0.6.0), the Odoo extension will have built-in odoo stubs, so we won't need to configure odoo stubs manually in VSCode anymore.

@trinhanhngoc How are you. I am also waiting for it every day <3

**Comment by trinhanhngoc** [comment]
> > Hello @daonamutc1 . In the next version (0.6.0), the Odoo extension will have built-in odoo stubs, so we won't need to configure odoo stubs manually in VSCode anymore.
> 
> @trinhanhngoc How are you. I am also waiting for it every day <3

Hello @tranngocson1996. I'm fine. It's nice to talk to other former Viindooers =)).

**Comment by tranngocson1996** [comment]
@trinhanhngoc former Viindooers. You know ??? 😸

**Comment by trinhanhngoc** [comment]
> @trinhanhngoc former Viindooers. You know ??? 😸

@ngochuy97hp, is @tranngocson1996 a former Viindooer?

**Comment by daonamutc1** [comment]
> > @trinhanhngoc former Viindooers. You know ??? 😸
> 
> @ngochuy97hp, is @tranngocson1996 a former Viindooer?

Yes, Mr. Son is a former Viindooer, just like me.

**Comment by trinhanhngoc** [comment]
Hi @daonamutc1. The new version 0.6.0 just released with built-in Odoo Stubs. You can remove the path settings for Odoo Stubs.

**Comment by daonamutc1** [comment]
> ttin

Thanks
